
#undef SSTREAM_PRE_RD
#undef SSTREAM_RD_STRUCT
#undef SSTREAM_RD_STRING
#undef SSTREAM_RD_FUNCTION
#undef SSTREAM_END_RD
#undef SSTREAM_PRE_WR
#undef SSTREAM_WR_STRUCT
#undef SSTREAM_WR_STRING
#undef SSTREAM_WR_FUNCTION
#undef SSTREAM_END_WR
